name: CD Workflow

on:
  push:
    branches:
      - main  # Quando um commit é enviado para o branch main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use a última versão do Ubuntu no GitHub Actions

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Faz o checkout do código no repositório

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Usando a versão 14 do Node.js

    - name: Install dependencies
      run: npm install  # Instala dependências (se o seu projeto usar npm)

    - name: Deploy to production
      run: |
        # Comandos específicos para realizar o deploy diretamente
        # Exemplo de deploy via SSH para um servidor
        ssh user@your-server-ip << 'EOF'
          cd /path/to/your/project
          git pull origin main
          npm install --production
          pm2 restart your-app-name  # ou o comando que reinicia seu servidor de produção
        EOF
