name: Run Tests on Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout o código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Garantir permissão para rodar o Jest
        run: chmod +x node_modules/.bin/jest

      - name: Rodar testes
        run: npm test
